/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as otpSol from "./OTP.sol";
export * as verifierSol from "./verifier.sol";
export { Greeter__factory } from "./Greeter__factory";
export { MyWallet__factory } from "./MyWallet__factory";
export { MyWalletDeployer__factory } from "./MyWalletDeployer__factory";
export { OTPFactory__factory } from "./OTPFactory__factory";
